#ifndef SECRETS_H
#define SECRETS_H

#define DEFAULT_HOUSE_SSID "YourSSID"
#define DEFAULT_HOUSE_PASSWORD "YourPassword"
#define DEFAULT_TRACTOR_SSID "FELLoader AP"
#define DEFAULT_TRACTOR_PASSWORD "12345678"

#endif