#ifndef SECRETS_H
#define SECRETS_H

#define DEFAULT_HOUSE_SSID "YourSSID"
#define DEFAULT_HOUSE_PASSWORD "YourPassword"
#define DEFAULT_TRACTOR_SSID "Tractor"
#define DEFAULT_TRACTOR_PASSWORD "12345678"

#define DEFAULT_AP_SSID "FEL AP"
#define DEFAULT_AP_PASSWORD "12345678"

#endif